export EDITOR=vim
export VISUAL=vim
export MOZ_ENABLE_WAYLAND=1
export QT_QPA_PLATFORM=wayland-egl
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export QT_WAYLAND_FORCE_DPI=physical
export FZF_DEFAULT_COMMAND='fd --hidden'
export FZF_ALT_C_COMMAND='fd --hidden'
export PATH="$HOME/.local/bin:$PATH"
ZDOTDIR="$HOME/.config/zsh"
